### ISSUE TITLE
能留个QQ或者微信交流吗

### ISSUE THREAD

**Issue by xiaokang-chen** [cllemon/ReactNativeSharedBook#1]
看了你写的程序，觉得你挺厉害的，RN坑着实的多，我现在正在学习当中。苦逼研究僧，导师让做混合开发，入了RN的坑，希望和大佬一起交流，共同进步！

**Comment by cllemon** [comment]
有什么能帮你的吗？ 如果有问题，可以在[react-native论坛](https://bbs.reactnative.cn/category/4/%E6%B1%82%E5%8A%A9%E4%B8%93%E5%8C%BA)里直接把问题贴出来，相信你能得到很好的答案。
